version: "3"
services:
  backend:
    build: ./backend
    container_name: 'redis_api_backend'
    command: sh -c 'npm install; npm start'
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/backend
    depends_on:
      - "db-redis"

  db-redis:
    container_name: 'db_redis_example'

    image: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: 'redis_api_frontend'
    image: node:16.20.0-alpine3.16
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - "backend"
    # working_dir: /home/tomasbidegain/Facultad/4to AÑO/bbdd-nsql/TP2/TP-redis/frontend
    stdin_open: true
    tty: true